// Copyright 2020 New Relic Corporation. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: sampleapp.proto

package sampleapp

import (
	"reflect"
	"sync"
	"unsafe"

	"google.golang.org/protobuf/reflect/protoreflect"
	"google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Message struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_sampleapp_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_sampleapp_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_sampleapp_proto_rawDescGZIP(), []int{0}
}

func (x *Message) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

var File_sampleapp_proto protoreflect.FileDescriptor

const file_sampleapp_proto_rawDesc = "" +
	"\n" +
	"\x0fsampleapp.proto\"\x1d\n" +
	"\aMessage\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text2\xb7\x01\n" +
	"\x11SampleApplication\x12$\n" +
	"\fDoUnaryUnary\x12\b.Message\x1a\b.Message\"\x00\x12'\n" +
	"\rDoUnaryStream\x12\b.Message\x1a\b.Message\"\x000\x01\x12'\n" +
	"\rDoStreamUnary\x12\b.Message\x1a\b.Message\"\x00(\x01\x12*\n" +
	"\x0eDoStreamStream\x12\b.Message\x1a\b.Message\"\x00(\x010\x01B\\B\x0eSampleappProtoP\x01ZHgithub.com/newrelic/go-agent/v3/integrations/nrconnect/example/sampleappb\x06proto3"

var (
	file_sampleapp_proto_rawDescOnce sync.Once
	file_sampleapp_proto_rawDescData []byte
)

func file_sampleapp_proto_rawDescGZIP() []byte {
	file_sampleapp_proto_rawDescOnce.Do(func() {
		file_sampleapp_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sampleapp_proto_rawDesc), len(file_sampleapp_proto_rawDesc)))
	})
	return file_sampleapp_proto_rawDescData
}

var file_sampleapp_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_sampleapp_proto_goTypes = []any{
	(*Message)(nil), // 0: Message
}
var file_sampleapp_proto_depIdxs = []int32{
	0, // 0: SampleApplication.DoUnaryUnary:input_type -> Message
	0, // 1: SampleApplication.DoUnaryStream:input_type -> Message
	0, // 2: SampleApplication.DoStreamUnary:input_type -> Message
	0, // 3: SampleApplication.DoStreamStream:input_type -> Message
	0, // 4: SampleApplication.DoUnaryUnary:output_type -> Message
	0, // 5: SampleApplication.DoUnaryStream:output_type -> Message
	0, // 6: SampleApplication.DoStreamUnary:output_type -> Message
	0, // 7: SampleApplication.DoStreamStream:output_type -> Message
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_sampleapp_proto_init() }
func file_sampleapp_proto_init() {
	if File_sampleapp_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sampleapp_proto_rawDesc), len(file_sampleapp_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_sampleapp_proto_goTypes,
		DependencyIndexes: file_sampleapp_proto_depIdxs,
		MessageInfos:      file_sampleapp_proto_msgTypes,
	}.Build()
	File_sampleapp_proto = out.File
	file_sampleapp_proto_goTypes = nil
	file_sampleapp_proto_depIdxs = nil
}
