// +build go1.9
// Code generated by protoc-gen-go. DO NOT EDIT.
// source: v3/internal/com_newrelic_trace_v1/v1.proto

package com_newrelic_trace_v1

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Span struct {
	TraceId              string                     `protobuf:"bytes,1,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	Intrinsics           map[string]*AttributeValue `protobuf:"bytes,2,rep,name=intrinsics,proto3" json:"intrinsics,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	UserAttributes       map[string]*AttributeValue `protobuf:"bytes,3,rep,name=user_attributes,json=userAttributes,proto3" json:"user_attributes,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	AgentAttributes      map[string]*AttributeValue `protobuf:"bytes,4,rep,name=agent_attributes,json=agentAttributes,proto3" json:"agent_attributes,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *Span) Reset()         { *m = Span{} }
func (m *Span) String() string { return proto.CompactTextString(m) }
func (*Span) ProtoMessage()    {}
func (*Span) Descriptor() ([]byte, []int) {
	return fileDescriptor_10a7bb7b83f0c5c3, []int{0}
}

func (m *Span) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Span.Unmarshal(m, b)
}
func (m *Span) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Span.Marshal(b, m, deterministic)
}
func (m *Span) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Span.Merge(m, src)
}
func (m *Span) XXX_Size() int {
	return xxx_messageInfo_Span.Size(m)
}
func (m *Span) XXX_DiscardUnknown() {
	xxx_messageInfo_Span.DiscardUnknown(m)
}

var xxx_messageInfo_Span proto.InternalMessageInfo

func (m *Span) GetTraceId() string {
	if m != nil {
		return m.TraceId
	}
	return ""
}

func (m *Span) GetIntrinsics() map[string]*AttributeValue {
	if m != nil {
		return m.Intrinsics
	}
	return nil
}

func (m *Span) GetUserAttributes() map[string]*AttributeValue {
	if m != nil {
		return m.UserAttributes
	}
	return nil
}

func (m *Span) GetAgentAttributes() map[string]*AttributeValue {
	if m != nil {
		return m.AgentAttributes
	}
	return nil
}

type AttributeValue struct {
	// Types that are valid to be assigned to Value:
	//	*AttributeValue_StringValue
	//	*AttributeValue_BoolValue
	//	*AttributeValue_IntValue
	//	*AttributeValue_DoubleValue
	Value                isAttributeValue_Value `protobuf_oneof:"value"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *AttributeValue) Reset()         { *m = AttributeValue{} }
func (m *AttributeValue) String() string { return proto.CompactTextString(m) }
func (*AttributeValue) ProtoMessage()    {}
func (*AttributeValue) Descriptor() ([]byte, []int) {
	return fileDescriptor_10a7bb7b83f0c5c3, []int{1}
}

func (m *AttributeValue) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AttributeValue.Unmarshal(m, b)
}
func (m *AttributeValue) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AttributeValue.Marshal(b, m, deterministic)
}
func (m *AttributeValue) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AttributeValue.Merge(m, src)
}
func (m *AttributeValue) XXX_Size() int {
	return xxx_messageInfo_AttributeValue.Size(m)
}
func (m *AttributeValue) XXX_DiscardUnknown() {
	xxx_messageInfo_AttributeValue.DiscardUnknown(m)
}

var xxx_messageInfo_AttributeValue proto.InternalMessageInfo

type isAttributeValue_Value interface {
	isAttributeValue_Value()
}

type AttributeValue_StringValue struct {
	StringValue string `protobuf:"bytes,1,opt,name=string_value,json=stringValue,proto3,oneof"`
}

type AttributeValue_BoolValue struct {
	BoolValue bool `protobuf:"varint,2,opt,name=bool_value,json=boolValue,proto3,oneof"`
}

type AttributeValue_IntValue struct {
	IntValue int64 `protobuf:"varint,3,opt,name=int_value,json=intValue,proto3,oneof"`
}

type AttributeValue_DoubleValue struct {
	DoubleValue float64 `protobuf:"fixed64,4,opt,name=double_value,json=doubleValue,proto3,oneof"`
}

func (*AttributeValue_StringValue) isAttributeValue_Value() {}

func (*AttributeValue_BoolValue) isAttributeValue_Value() {}

func (*AttributeValue_IntValue) isAttributeValue_Value() {}

func (*AttributeValue_DoubleValue) isAttributeValue_Value() {}

func (m *AttributeValue) GetValue() isAttributeValue_Value {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *AttributeValue) GetStringValue() string {
	if x, ok := m.GetValue().(*AttributeValue_StringValue); ok {
		return x.StringValue
	}
	return ""
}

func (m *AttributeValue) GetBoolValue() bool {
	if x, ok := m.GetValue().(*AttributeValue_BoolValue); ok {
		return x.BoolValue
	}
	return false
}

func (m *AttributeValue) GetIntValue() int64 {
	if x, ok := m.GetValue().(*AttributeValue_IntValue); ok {
		return x.IntValue
	}
	return 0
}

func (m *AttributeValue) GetDoubleValue() float64 {
	if x, ok := m.GetValue().(*AttributeValue_DoubleValue); ok {
		return x.DoubleValue
	}
	return 0
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*AttributeValue) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*AttributeValue_StringValue)(nil),
		(*AttributeValue_BoolValue)(nil),
		(*AttributeValue_IntValue)(nil),
		(*AttributeValue_DoubleValue)(nil),
	}
}

type RecordStatus struct {
	MessagesSeen         uint64   `protobuf:"varint,1,opt,name=messages_seen,json=messagesSeen,proto3" json:"messages_seen,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RecordStatus) Reset()         { *m = RecordStatus{} }
func (m *RecordStatus) String() string { return proto.CompactTextString(m) }
func (*RecordStatus) ProtoMessage()    {}
func (*RecordStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_10a7bb7b83f0c5c3, []int{2}
}

func (m *RecordStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RecordStatus.Unmarshal(m, b)
}
func (m *RecordStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RecordStatus.Marshal(b, m, deterministic)
}
func (m *RecordStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RecordStatus.Merge(m, src)
}
func (m *RecordStatus) XXX_Size() int {
	return xxx_messageInfo_RecordStatus.Size(m)
}
func (m *RecordStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_RecordStatus.DiscardUnknown(m)
}

var xxx_messageInfo_RecordStatus proto.InternalMessageInfo

func (m *RecordStatus) GetMessagesSeen() uint64 {
	if m != nil {
		return m.MessagesSeen
	}
	return 0
}

func init() {
	proto.RegisterType((*Span)(nil), "com.newrelic.trace.v1.Span")
	proto.RegisterMapType((map[string]*AttributeValue)(nil), "com.newrelic.trace.v1.Span.AgentAttributesEntry")
	proto.RegisterMapType((map[string]*AttributeValue)(nil), "com.newrelic.trace.v1.Span.IntrinsicsEntry")
	proto.RegisterMapType((map[string]*AttributeValue)(nil), "com.newrelic.trace.v1.Span.UserAttributesEntry")
	proto.RegisterType((*AttributeValue)(nil), "com.newrelic.trace.v1.AttributeValue")
	proto.RegisterType((*RecordStatus)(nil), "com.newrelic.trace.v1.RecordStatus")
}

func init() {
	proto.RegisterFile("v3/internal/com_newrelic_trace_v1/v1.proto", fileDescriptor_10a7bb7b83f0c5c3)
}

var fileDescriptor_10a7bb7b83f0c5c3 = []byte{
	// 465 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x94, 0xdf, 0x8a, 0xd3, 0x40,
	0x14, 0xc6, 0x3b, 0x6d, 0x74, 0xdb, 0xd3, 0xee, 0x76, 0x19, 0x15, 0x6a, 0x45, 0x0c, 0x2d, 0x42,
	0x50, 0x4c, 0xb6, 0xed, 0x8d, 0x28, 0x88, 0xbb, 0x20, 0xb4, 0x78, 0x97, 0xaa, 0x88, 0x5e, 0x84,
	0xfc, 0x39, 0x64, 0x07, 0xd3, 0xc9, 0x32, 0x33, 0x89, 0xec, 0xf3, 0xf8, 0x62, 0x3e, 0x8a, 0xcc,
	0x24, 0xad, 0xed, 0xd2, 0xed, 0x5e, 0xed, 0x5d, 0x72, 0xce, 0xf7, 0xfd, 0xbe, 0x39, 0xc3, 0xcc,
	0xc0, 0xab, 0x72, 0xe6, 0x31, 0xae, 0x50, 0xf0, 0x30, 0xf3, 0xe2, 0x7c, 0x15, 0x70, 0xfc, 0x2d,
	0x30, 0x63, 0x71, 0xa0, 0x44, 0x18, 0x63, 0x50, 0x4e, 0xbc, 0x72, 0xe2, 0x5e, 0x89, 0x5c, 0xe5,
	0xf4, 0x49, 0x9c, 0xaf, 0xdc, 0x75, 0xdf, 0x35, 0x7d, 0xb7, 0x9c, 0x8c, 0xfe, 0x5a, 0x60, 0x2d,
	0xaf, 0x42, 0x4e, 0x9f, 0x42, 0xbb, 0x32, 0xb1, 0x64, 0x40, 0x6c, 0xe2, 0x74, 0xfc, 0x23, 0xf3,
	0xbf, 0x48, 0xe8, 0x67, 0x00, 0xc6, 0x95, 0x60, 0x5c, 0xb2, 0x58, 0x0e, 0x9a, 0x76, 0xcb, 0xe9,
	0x4e, 0x5f, 0xbb, 0x7b, 0x79, 0xae, 0x66, 0xb9, 0x8b, 0x8d, 0xfa, 0x13, 0x57, 0xe2, 0xda, 0xdf,
	0xb2, 0xd3, 0xef, 0xd0, 0x2f, 0x24, 0x8a, 0x20, 0x54, 0x4a, 0xb0, 0xa8, 0x50, 0x28, 0x07, 0x2d,
	0x43, 0xf4, 0x0e, 0x11, 0xbf, 0x4a, 0x14, 0xe7, 0x1b, 0x47, 0x45, 0x3d, 0x29, 0x76, 0x8a, 0xf4,
	0x27, 0x9c, 0x86, 0x29, 0x72, 0xb5, 0x8d, 0xb6, 0x0c, 0xfa, 0xec, 0x10, 0xfa, 0x5c, 0x7b, 0x6e,
	0xb2, 0xfb, 0xe1, 0x6e, 0x75, 0x98, 0x40, 0xff, 0xc6, 0x54, 0xf4, 0x14, 0x5a, 0xbf, 0xf0, 0xba,
	0xde, 0x2c, 0xfd, 0x49, 0xdf, 0xc3, 0x83, 0x32, 0xcc, 0x0a, 0x1c, 0x34, 0x6d, 0xe2, 0x74, 0xa7,
	0x2f, 0x6f, 0x89, 0xdd, 0x60, 0xbf, 0x69, 0xb1, 0x5f, 0x79, 0xde, 0x35, 0xdf, 0x92, 0xe1, 0x25,
	0x3c, 0xda, 0x33, 0xe9, 0x7d, 0x24, 0x31, 0x78, 0xbc, 0x6f, 0xf0, 0x7b, 0x88, 0x1a, 0xfd, 0x21,
	0x70, 0xb2, 0xdb, 0xa5, 0x63, 0xe8, 0x49, 0xbd, 0x99, 0x69, 0x50, 0xa1, 0x4d, 0xdc, 0xbc, 0xe1,
	0x77, 0xab, 0x6a, 0x25, 0x7a, 0x01, 0x10, 0xe5, 0x79, 0x16, 0xfc, 0x4f, 0x6f, 0xcf, 0x1b, 0x7e,
	0x47, 0xd7, 0x2a, 0xc1, 0x73, 0xe8, 0x30, 0xae, 0xea, 0x7e, 0xcb, 0x26, 0x4e, 0x6b, 0xde, 0xf0,
	0xdb, 0x8c, 0xab, 0x4d, 0x48, 0x92, 0x17, 0x51, 0x86, 0xb5, 0xc2, 0xb2, 0x89, 0x43, 0x74, 0x48,
	0x55, 0x35, 0xa2, 0x8b, 0xa3, 0x7a, 0xba, 0xd1, 0x0c, 0x7a, 0x3e, 0xc6, 0xb9, 0x48, 0x96, 0x2a,
	0x54, 0x85, 0xa4, 0x63, 0x38, 0x5e, 0xa1, 0x94, 0x61, 0x8a, 0x32, 0x90, 0x88, 0xdc, 0xac, 0xd1,
	0xf2, 0x7b, 0xeb, 0xe2, 0x12, 0x91, 0x4f, 0x11, 0x8e, 0x17, 0x3c, 0x45, 0xa9, 0x96, 0x28, 0x4a,
	0x16, 0x23, 0xfd, 0x02, 0x50, 0x53, 0xf4, 0x9d, 0x7a, 0x76, 0xe0, 0xdc, 0x0d, 0xc7, 0xb7, 0x34,
	0xb7, 0x57, 0x31, 0x6a, 0x38, 0xe4, 0x8c, 0x5c, 0x7c, 0xfc, 0xf1, 0x21, 0x65, 0xea, 0xb2, 0x88,
	0xb4, 0xc5, 0x5b, 0x5b, 0xbc, 0x34, 0x7f, 0x63, 0x8e, 0xa9, 0x77, 0xe7, 0x33, 0x10, 0x3d, 0x34,
	0x8f, 0xc0, 0xec, 0x5f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x76, 0xb2, 0x84, 0xe9, 0x32, 0x04, 0x00,
	0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// IngestServiceClient is the client API for IngestService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type IngestServiceClient interface {
	// Accepts a stream of Span messages, and returns an irregular stream of
	// RecordStatus messages.
	RecordSpan(ctx context.Context, opts ...grpc.CallOption) (IngestService_RecordSpanClient, error)
}

type ingestServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewIngestServiceClient(cc grpc.ClientConnInterface) IngestServiceClient {
	return &ingestServiceClient{cc}
}

func (c *ingestServiceClient) RecordSpan(ctx context.Context, opts ...grpc.CallOption) (IngestService_RecordSpanClient, error) {
	stream, err := c.cc.NewStream(ctx, &_IngestService_serviceDesc.Streams[0], "/com.newrelic.trace.v1.IngestService/RecordSpan", opts...)
	if err != nil {
		return nil, err
	}
	x := &ingestServiceRecordSpanClient{stream}
	return x, nil
}

type IngestService_RecordSpanClient interface {
	Send(*Span) error
	Recv() (*RecordStatus, error)
	grpc.ClientStream
}

type ingestServiceRecordSpanClient struct {
	grpc.ClientStream
}

func (x *ingestServiceRecordSpanClient) Send(m *Span) error {
	return x.ClientStream.SendMsg(m)
}

func (x *ingestServiceRecordSpanClient) Recv() (*RecordStatus, error) {
	m := new(RecordStatus)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// IngestServiceServer is the server API for IngestService service.
type IngestServiceServer interface {
	// Accepts a stream of Span messages, and returns an irregular stream of
	// RecordStatus messages.
	RecordSpan(IngestService_RecordSpanServer) error
}

// UnimplementedIngestServiceServer can be embedded to have forward compatible implementations.
type UnimplementedIngestServiceServer struct {
}

func (*UnimplementedIngestServiceServer) RecordSpan(srv IngestService_RecordSpanServer) error {
	return status.Errorf(codes.Unimplemented, "method RecordSpan not implemented")
}

func RegisterIngestServiceServer(s *grpc.Server, srv IngestServiceServer) {
	s.RegisterService(&_IngestService_serviceDesc, srv)
}

func _IngestService_RecordSpan_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(IngestServiceServer).RecordSpan(&ingestServiceRecordSpanServer{stream})
}

type IngestService_RecordSpanServer interface {
	Send(*RecordStatus) error
	Recv() (*Span, error)
	grpc.ServerStream
}

type ingestServiceRecordSpanServer struct {
	grpc.ServerStream
}

func (x *ingestServiceRecordSpanServer) Send(m *RecordStatus) error {
	return x.ServerStream.SendMsg(m)
}

func (x *ingestServiceRecordSpanServer) Recv() (*Span, error) {
	m := new(Span)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _IngestService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "com.newrelic.trace.v1.IngestService",
	HandlerType: (*IngestServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "RecordSpan",
			Handler:       _IngestService_RecordSpan_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "v3/internal/com_newrelic_trace_v1/v1.proto",
}
