// Copyright 2020 New Relic Corporation. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: testapp.proto

package testapp

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Message struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_testapp_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_testapp_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_testapp_proto_rawDescGZIP(), []int{0}
}

func (x *Message) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

var File_testapp_proto protoreflect.FileDescriptor

const file_testapp_proto_rawDesc = "" +
	"\n" +
	"\rtestapp.proto\"\x1d\n" +
	"\aMessage\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text2\x8e\x02\n" +
	"\x0fTestApplication\x12$\n" +
	"\fDoUnaryUnary\x12\b.Message\x1a\b.Message\"\x00\x12'\n" +
	"\rDoUnaryStream\x12\b.Message\x1a\b.Message\"\x000\x01\x12'\n" +
	"\rDoStreamUnary\x12\b.Message\x1a\b.Message\"\x00(\x01\x12*\n" +
	"\x0eDoStreamStream\x12\b.Message\x1a\b.Message\"\x00(\x010\x01\x12)\n" +
	"\x11DoUnaryUnaryError\x12\b.Message\x1a\b.Message\"\x00\x12,\n" +
	"\x12DoUnaryStreamError\x12\b.Message\x1a\b.Message\"\x000\x01BPB\fTestappProtoP\x01Z>github.com/newrelic/go-agent/v3/integrations/nrconnect/testappb\x06proto3"

var (
	file_testapp_proto_rawDescOnce sync.Once
	file_testapp_proto_rawDescData []byte
)

func file_testapp_proto_rawDescGZIP() []byte {
	file_testapp_proto_rawDescOnce.Do(func() {
		file_testapp_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_testapp_proto_rawDesc), len(file_testapp_proto_rawDesc)))
	})
	return file_testapp_proto_rawDescData
}

var file_testapp_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_testapp_proto_goTypes = []any{
	(*Message)(nil), // 0: Message
}
var file_testapp_proto_depIdxs = []int32{
	0, // 0: TestApplication.DoUnaryUnary:input_type -> Message
	0, // 1: TestApplication.DoUnaryStream:input_type -> Message
	0, // 2: TestApplication.DoStreamUnary:input_type -> Message
	0, // 3: TestApplication.DoStreamStream:input_type -> Message
	0, // 4: TestApplication.DoUnaryUnaryError:input_type -> Message
	0, // 5: TestApplication.DoUnaryStreamError:input_type -> Message
	0, // 6: TestApplication.DoUnaryUnary:output_type -> Message
	0, // 7: TestApplication.DoUnaryStream:output_type -> Message
	0, // 8: TestApplication.DoStreamUnary:output_type -> Message
	0, // 9: TestApplication.DoStreamStream:output_type -> Message
	0, // 10: TestApplication.DoUnaryUnaryError:output_type -> Message
	0, // 11: TestApplication.DoUnaryStreamError:output_type -> Message
	6, // [6:12] is the sub-list for method output_type
	0, // [0:6] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_testapp_proto_init() }
func file_testapp_proto_init() {
	if File_testapp_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_testapp_proto_rawDesc), len(file_testapp_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_testapp_proto_goTypes,
		DependencyIndexes: file_testapp_proto_depIdxs,
		MessageInfos:      file_testapp_proto_msgTypes,
	}.Build()
	File_testapp_proto = out.File
	file_testapp_proto_goTypes = nil
	file_testapp_proto_depIdxs = nil
}
